### ISSUE TITLE
Formatting issues on end of lines

### ISSUE THREAD

**Issue by ludelafo** [swiss-ai-center/mdwrap#7]
I think I have spotted some litte issues with mdwrap.

For the given Markdown document (taken from https://github.com/swiss-ai-center/a-guide-to-mlops/blob/main/presentation/README.md, please notice the double spaces (`··`) at the end of the sentence):

```md
## Access the guide

<!-- _class: lead -->

Access the guide at  
[mlops.swiss-ai-center.ch](https://mlops.swiss-ai-center.ch)
```

When I check if the file needs to be formatted, mdwrap does not complain:

```sh
mdwrap --check demo.md
```

Output:

```text
Checking files...
SUCCESS: Checks passed. All files are formatted.
```

However, when I format the files, mdwrap formats it:

```sh
mdwrap --fmt demo.md
```

Output:

```text
demo.md (file is formatted)
```

The result is as shown (please note that the two remaining spaces are gone, and it is against the common Markdown specifications):

```md
## Access the guide

<!-- _class: lead -->

Access the guide at
[mlops.swiss-ai-center.ch](https://mlops.swiss-ai-center.ch)
```

If I run the same command without the `--fmt` argument, it does not format the document:

```sh
mdwrap demo.md
```

Output:

```text
demo.md (file is not formatted)
```

Another interesting thing is if I remove the HTML comment, then the check fails:

```md
## Access the guide

Access the guide at  
[mlops.swiss-ai-center.ch](https://mlops.swiss-ai-center.ch)
```

```sh
mdwrap --check demo.md
```

Output:

```text
Checking files...
demo.md
ERROR: Checks failed. The files above are not formatted. (hint: run 'mdwrap [targets ...]' to format them)
```

And when I format the document, mdwrap puts all on one line (notice this time mdwrap formats the document using both commands):

```sh
mdwrap --fmt demo.md

# OR

mdwrap demo.md
```

Output:

```text
demo.md (file is formatted)
```

Results:

```md
## Access the guide

Access the guide at [mlops.swiss-ai-center.ch](https://mlops.swiss-ai-center.ch)
```

Let me know if I can be of any help.

**Comment by leonardcser** [comment]
To address both behaviours, the first case is not really clear but when mdwrap is called without `--fmt`, it just wraps lines. So `mdwrap --check ...`, just checks if lines are wrapped correctly. In order to check for formatting, mdwrap should be called with `mdwrap --fmt --check ...`.

The second behaviour is that mdwrap did not support html comments. It also explains why in the first example the --check is successful. This has been added in #10
